# Labeler configuration for auto-labeling PRs based on file paths
# See: https://github.com/actions/labeler
# Format: label-name: [array of file patterns]

# Authentication & Authorization
'area:auth':
  - lib/features/auth/**
  - test/**/auth_*_test.dart

# Chat feature
'area:chat':
  - lib/features/chat/**
  - test/**/chat_*_test.dart

# Core functionality
'area:core':
  - lib/core/**
  - test/utils/**

# Home screen
'area:home':
  - lib/features/home/**
  - test/**/home_*_test.dart

# Onboarding
'area:onboarding':
  - lib/features/onboarding/**
  - test/**/onboarding_*_test.dart

# Permissions
'area:permissions':
  - lib/features/permissions/**
  - test/**/permissions_*_test.dart

# Profile
'area:profile':
  - lib/features/profile/**
  - test/**/profile_*_test.dart

# Settings
'area:settings':
  - lib/features/settings/**
  - test/**/settings_*_test.dart

# Setup
'area:setup':
  - lib/features/setup/**
  - test/**/setup_*_test.dart

# Splash
'area:splash':
  - lib/features/splash/**
  - test/**/splash_*_test.dart

# Analytics
'area:analytics':
  - lib/features/analytics/**
  - test/**/analytics_*_test.dart

# Subscription
'area:subscription':
  - lib/features/subscription/**
  - test/**/subscription_*_test.dart

# Tests
'area:tests':
  - test/**

# CI/CD
'area:ci':
  - .github/workflows/**
  - .github/actions/**

# Documentation
'area:docs':
  - docs/**
  - '*.md'
  - README.md

# Dependencies
'area:dependencies':
  - pubspec.yaml
  - pubspec.lock

# Infrastructure
'area:infrastructure':
  - tool/**
  - android/**
  - ios/**
  - web/**

