name: Feature Request
description: Suggest an idea for this project
title: '[FEATURE] '
labels: ['feature']
assignees: ''

body:
  - type: textarea
    id: problem
    attributes:
      label: Problem / Context
      description: Describe the problem or context that this feature would solve
      placeholder: What problem does this feature solve?
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: How should this feature work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: What other approaches did you consider?
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request
      placeholder: Screenshots, mockups, or examples...

