// File generated by flutterfire configure
// This is a stub file. In production, run `flutterfire configure` to generate the actual file.
// For now, this allows the code to compile. Firebase will use platform-specific config files:
// - iOS: ios/Runner/GoogleService-Info.plist
// - Android: android/app/google-services.json

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'android-api-key-placeholder',
    appId: 'android-app-id-placeholder',
    messagingSenderId: 'messaging-sender-id-placeholder',
    projectId: 'project-id-placeholder',
    storageBucket: 'storage-bucket-placeholder',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'ios-api-key-placeholder',
    appId: 'ios-app-id-placeholder',
    messagingSenderId: 'messaging-sender-id-placeholder',
    projectId: 'project-id-placeholder',
    storageBucket: 'storage-bucket-placeholder',
    iosBundleId: 'com.iammara.maraApp',
  );
}
